165
2068280201847696707727644411099609233271492220857010176394014351464441877294196933672390357053708518311042278063202279659124481730871403275342471781647275
-------------------------------------------------------------------------------------------------
2068280201847696707727644411099609233271492220857010176394014351464441877294196933672390357053708518311042278063202279659124481730871403275342471781647275
-------------------------------------------------------------------------------------------------
2068280201847696707727644411099609233271492220857010176394014351464441877294196933672390357053708518311042278063202279659124481730871403275342471781647275
-------------------------------------------------------------------------------------------------
2068280201847696707727644411099609233271492220857010176394014351464441877294196933672390357053708518311042278063202279659124481730871403275342471781647275
-------------------------------------------------------------------------------------------------



165
7302645867515137416704330417036841775264447121476815988201159396813961801303463934755824907322668112211151196929754770898426196891543896072498055274311402
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
1935238120683837779636948818792521118433857206704891402598131217711089892414969076916512981672037305716372763657199262404590864913490317405079785887708363
-------------------------------------------------------------------------------------------------
1935238120683837779636948818792521118433857206704891402598131217711089892414969076916512981672037305716372763657199262404590864913490317405079785887708363
-------------------------------------------------------------------------------------------------
1935238120683837779636948818792521118433857206704891402598131217711089892414969076916512981672037305716372763657199262404590864913490317405079785887708363
-------------------------------------------------------------------------------------------------
1935238120683837779636948818792521118433857206704891402598131217711089892414969076916512981672037305716372763657199262404590864913490317405079785887708363
-------------------------------------------------------------------------------------------------



165
5203200489904718685969831910651220291507129270526705720226645970168112989501396752594911453268035984894872673966274189928750848713366150959366130292867389
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
5203200489904718685969831910651220291507129270526705720226645970168112989501396752594911453268035984894872673966274189928750848713366150959366130292867389
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
4382261166942271134926871706963677966603413998521990888441986857836424513125530212338880544311432402699398426835349655983006445694754307571418621214870071
-------------------------------------------------------------------------------------------------
4382261166942271134926871706963677966603413998521990888441986857836424513125530212338880544311432402699398426835349655983006445694754307571418621214870071
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
4382261166942271134926871706963677966603413998521990888441986857836424513125530212338880544311432402699398426835349655983006445694754307571418621214870071
-------------------------------------------------------------------------------------------------



165
4226902018734601027087484407729151421024268339468483943748074808141592404592529636050791816002387896354249778170896072231672508632261124488729498934273993
-------------------------------------------------------------------------------------------------
4226902018734601027087484407729151421024268339468483943748074808141592404592529636050791816002387896354249778170896072231672508632261124488729498934273993
-------------------------------------------------------------------------------------------------
4226902018734601027087484407729151421024268339468483943748074808141592404592529636050791816002387896354249778170896072231672508632261124488729498934273993
-------------------------------------------------------------------------------------------------
4226902018734601027087484407729151421024268339468483943748074808141592404592529636050791816002387896354249778170896072231672508632261124488729498934273993
-------------------------------------------------------------------------------------------------



165
788544236369817212036104034071401311478979944819672675195791887971674603149870764531099987430295335976880132213613774170932436075307219752641044759814604
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8179740508254136056196802114306927159231104164607635116075297917471195004152453315520036389360788331737394454299711215569085992835149728168294125063819501
-------------------------------------------------------------------------------------------------
8179740508254136056196802114306927159231104164607635116075297917471195004152453315520036389360788331737394454299711215569085992835149728168294125063819501
-------------------------------------------------------------------------------------------------
8179740508254136056196802114306927159231104164607635116075297917471195004152453315520036389360788331737394454299711215569085992835149728168294125063819501
-------------------------------------------------------------------------------------------------
8179740508254136056196802114306927159231104164607635116075297917471195004152453315520036389360788331737394454299711215569085992835149728168294125063819501
-------------------------------------------------------------------------------------------------



165
5797674379894768520576593752108008075015810417824209953614226668737116469893690812388356576609077128689634560183587805913534120029799716738463455568410029
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
5797674379894768520576593752108008075015810417824209953614226668737116469893690812388356576609077128689634560183587805913534120029799716738463455568410029
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
7063896916121046868273667889338174811644092368876796464985454904889838275023423823658539896347204820052157504786936472865013089418606051983883671271708006
-------------------------------------------------------------------------------------------------
7063896916121046868273667889338174811644092368876796464985454904889838275023423823658539896347204820052157504786936472865013089418606051983883671271708006
-------------------------------------------------------------------------------------------------
7063896916121046868273667889338174811644092368876796464985454904889838275023423823658539896347204820052157504786936472865013089418606051983883671271708006
-------------------------------------------------------------------------------------------------
7063896916121046868273667889338174811644092368876796464985454904889838275023423823658539896347204820052157504786936472865013089418606051983883671271708006
-------------------------------------------------------------------------------------------------



165
11983169165285894968157457288309785208555693975754469407789207784712730107946652809543176707750727621141127752151419952760458750747619178782737711121005906
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
12506201905422684661494531859558291181696854169243396122623522073095542173959476222344741870351952213346449768899592740139863545753417952549306346744638538
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
6826480471221266616194668926873520328868523161133931079634966715959378590641524748534754226094196057789202741139314730256201759424980309395850226768850761
-------------------------------------------------------------------------------------------------
6826480471221266616194668926873520328868523161133931079634966715959378590641524748534754226094196057789202741139314730256201759424980309395850226768850761
-------------------------------------------------------------------------------------------------
6826480471221266616194668926873520328868523161133931079634966715959378590641524748534754226094196057789202741139314730256201759424980309395850226768850761
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
10315554220258299795759443115046909184423204941170878519744514344973208319889885187043815088892923379328495875129572867978152270029296305582732572638677094
-------------------------------------------------------------------------------------------------
10315554220258299795759443115046909184423204941170878519744514344973208319889885187043815088892923379328495875129572867978152270029296305582732572638677094
-------------------------------------------------------------------------------------------------
10315554220258299795759443115046909184423204941170878519744514344973208319889885187043815088892923379328495875129572867978152270029296305582732572638677094
-------------------------------------------------------------------------------------------------
10315554220258299795759443115046909184423204941170878519744514344973208319889885187043815088892923379328495875129572867978152270029296305582732572638677094
-------------------------------------------------------------------------------------------------



165
5528009960420004981643998803847395531334232378672676063578227027104927319721502276119017986030910874397743747918076021628788875812425253421675018041696845
-------------------------------------------------------------------------------------------------
5528009960420004981643998803847395531334232378672676063578227027104927319721502276119017986030910874397743747918076021628788875812425253421675018041696845
-------------------------------------------------------------------------------------------------
5528009960420004981643998803847395531334232378672676063578227027104927319721502276119017986030910874397743747918076021628788875812425253421675018041696845
-------------------------------------------------------------------------------------------------
5528009960420004981643998803847395531334232378672676063578227027104927319721502276119017986030910874397743747918076021628788875812425253421675018041696845
-------------------------------------------------------------------------------------------------



165
8500465318117817817192783407738324834577685102791231977637690387859129565417879744331204749173455575028748432511308630695850337901302999892066074004979439
-------------------------------------------------------------------------------------------------
8500465318117817817192783407738324834577685102791231977637690387859129565417879744331204749173455575028748432511308630695850337901302999892066074004979439
-------------------------------------------------------------------------------------------------
8500465318117817817192783407738324834577685102791231977637690387859129565417879744331204749173455575028748432511308630695850337901302999892066074004979439
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
1300756289661298915048975825401979907914716441183735411447778565088211521407799990828816870649146538573282700996653505756399988145655232764263236674335538
-------------------------------------------------------------------------------------------------
1300756289661298915048975825401979907914716441183735411447778565088211521407799990828816870649146538573282700996653505756399988145655232764263236674335538
-------------------------------------------------------------------------------------------------
1300756289661298915048975825401979907914716441183735411447778565088211521407799990828816870649146538573282700996653505756399988145655232764263236674335538
-------------------------------------------------------------------------------------------------
1300756289661298915048975825401979907914716441183735411447778565088211521407799990828816870649146538573282700996653505756399988145655232764263236674335538
-------------------------------------------------------------------------------------------------



165
7576875367904636907822057019434667170578453007435544585277638699620485386831318920696216856013084473362425187445845900495035277372773122625320916975328611
-------------------------------------------------------------------------------------------------
7576875367904636907822057019434667170578453007435544585277638699620485386831318920696216856013084473362425187445845900495035277372773122625320916975328611
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
5997360704622906326550472681627477533898680452427765355875843299062160968667965856866253060938683125759807788713732453457382141338025874425052823008727285
-------------------------------------------------------------------------------------------------
5997360704622906326550472681627477533898680452427765355875843299062160968667965856866253060938683125759807788713732453457382141338025874425052823008727285
-------------------------------------------------------------------------------------------------
5997360704622906326550472681627477533898680452427765355875843299062160968667965856866253060938683125759807788713732453457382141338025874425052823008727285
-------------------------------------------------------------------------------------------------
5997360704622906326550472681627477533898680452427765355875843299062160968667965856866253060938683125759807788713732453457382141338025874425052823008727285
-------------------------------------------------------------------------------------------------



165
9660737574883381415454374655704640234259237118756987478418381561418888553225552654821131806738298626785602749105327720529888925102297365259534474752707263
-------------------------------------------------------------------------------------------------
9660737574883381415454374655704640234259237118756987478418381561418888553225552654821131806738298626785602749105327720529888925102297365259534474752707263
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
9660737574883381415454374655704640234259237118756987478418381561418888553225552654821131806738298626785602749105327720529888925102297365259534474752707263
-------------------------------------------------------------------------------------------------



165
42530295210138818537368383621710847534791535054748569081091169649626387455116009770554251974003316997254431560115883935001562821583777732703478352692733
-------------------------------------------------------------------------------------------------
42530295210138818537368383621710847534791535054748569081091169649626387455116009770554251974003316997254431560115883935001562821583777732703478352692733
-------------------------------------------------------------------------------------------------
42530295210138818537368383621710847534791535054748569081091169649626387455116009770554251974003316997254431560115883935001562821583777732703478352692733
-------------------------------------------------------------------------------------------------
42530295210138818537368383621710847534791535054748569081091169649626387455116009770554251974003316997254431560115883935001562821583777732703478352692733
-------------------------------------------------------------------------------------------------



165
9567351774157201527676879951951407655246317172891933580535574318205530374169474497209697060809439633728759579670390166298287526555886518446903457202090818
-------------------------------------------------------------------------------------------------
9567351774157201527676879951951407655246317172891933580535574318205530374169474497209697060809439633728759579670390166298287526555886518446903457202090818
-------------------------------------------------------------------------------------------------
9567351774157201527676879951951407655246317172891933580535574318205530374169474497209697060809439633728759579670390166298287526555886518446903457202090818
-------------------------------------------------------------------------------------------------
9567351774157201527676879951951407655246317172891933580535574318205530374169474497209697060809439633728759579670390166298287526555886518446903457202090818
-------------------------------------------------------------------------------------------------



165
9264021354354691038127058953427949645190576838882743048226750136626101661218825372268932112265959918281668370442326450964984264892679459326153240228020556
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 750, in rs_correct_msg
    err_pos = rs_find_errors(err_loc[::-1], len(msg_out), generator)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 694, in rs_find_errors
    raise ReedSolomonError("Too many (or few) errors found by Chien Search for the errata locator polynomial!")
reedsolo.ReedSolomonError: Too many (or few) errors found by Chien Search for the errata locator polynomial!

Wrong user!
-------------------------------------------------------------------------------------------------
9264021354354691038127058953427949645190576838882743048226750136626101661218825372268932112265959918281668370442326450964984264892679459326153240228020556
-------------------------------------------------------------------------------------------------
9264021354354691038127058953427949645190576838882743048226750136626101661218825372268932112265959918281668370442326450964984264892679459326153240228020556
-------------------------------------------------------------------------------------------------



165
7470714016199484964624162350395116374657236785514254168120068119775273579186451177994477137057904906809783056986579098209095975383759028268472473648033688
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8092757156839058246296403625692819557587029162865259071631122739258074816799708633962392484612287989482277006559957546186176121956610680002681668630798578
-------------------------------------------------------------------------------------------------
8092757156839058246296403625692819557587029162865259071631122739258074816799708633962392484612287989482277006559957546186176121956610680002681668630798578
-------------------------------------------------------------------------------------------------
8092757156839058246296403625692819557587029162865259071631122739258074816799708633962392484612287989482277006559957546186176121956610680002681668630798578
-------------------------------------------------------------------------------------------------
8092757156839058246296403625692819557587029162865259071631122739258074816799708633962392484612287989482277006559957546186176121956610680002681668630798578
-------------------------------------------------------------------------------------------------



165
12330531754761403992497771396609990201450753358458110701121250950227890301279578980633470205528234195042329247631880493201103733066190068635327761764240268
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
12330531754761403992497771396609990201450753358458110701121250950227890301279578980633470205528234195042329247631880493201103733066190068635327761764240268
-------------------------------------------------------------------------------------------------



165
4726491058353150938378480024246637721359911341700856960080851473367070139152395454738874345123001465318727103009492815516328531038391833201065992085931346
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
13273925003339655715050583686240662943186497169118450513690798009079604044541157217128309655514027451010487752928292053712213975683617250043857770475725675
-------------------------------------------------------------------------------------------------
13273925003339655715050583686240662943186497169118450513690798009079604044541157217128309655514027451010487752928292053712213975683617250043857770475725675
-------------------------------------------------------------------------------------------------
13273925003339655715050583686240662943186497169118450513690798009079604044541157217128309655514027451010487752928292053712213975683617250043857770475725675
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
5649355734733324035544141894373639556155321341889424954268879856212750614467700136880747950624666837810658989712567672758525106869519874021208680181641409
-------------------------------------------------------------------------------------------------
5649355734733324035544141894373639556155321341889424954268879856212750614467700136880747950624666837810658989712567672758525106869519874021208680181641409
-------------------------------------------------------------------------------------------------
5649355734733324035544141894373639556155321341889424954268879856212750614467700136880747950624666837810658989712567672758525106869519874021208680181641409
-------------------------------------------------------------------------------------------------
5649355734733324035544141894373639556155321341889424954268879856212750614467700136880747950624666837810658989712567672758525106869519874021208680181641409
-------------------------------------------------------------------------------------------------



165
7431756688802818638562345687038906986402682052206895464392894330869970827117960224728282069674446645981967377902294151229838739893676397674899620890763165
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
7431756688802818638562345687038906986402682052206895464392894330869970827117960224728282069674446645981967377902294151229838739893676397674899620890763165
-------------------------------------------------------------------------------------------------
7431756688802818638562345687038906986402682052206895464392894330869970827117960224728282069674446645981967377902294151229838739893676397674899620890763165
-------------------------------------------------------------------------------------------------



165
6739373460368878238817844383416673030471324812523828453022638623021794427908015395344439808154559361721706039539622011930492936014984251255786593145889066
-------------------------------------------------------------------------------------------------
6739373460368878238817844383416673030471324812523828453022638623021794427908015395344439808154559361721706039539622011930492936014984251255786593145889066
-------------------------------------------------------------------------------------------------
6739373460368878238817844383416673030471324812523828453022638623021794427908015395344439808154559361721706039539622011930492936014984251255786593145889066
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
12104927389385665456056014749346846094880105465877062027455988177872494976461348829328978131304603039876657424020173902870549180046103771471882558863578310
-------------------------------------------------------------------------------------------------
12104927389385665456056014749346846094880105465877062027455988177872494976461348829328978131304603039876657424020173902870549180046103771471882558863578310
-------------------------------------------------------------------------------------------------
12104927389385665456056014749346846094880105465877062027455988177872494976461348829328978131304603039876657424020173902870549180046103771471882558863578310
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8792893478724906376346595940397381414660944059455444526883826702343071776391783679870245781731806560482766608548081581236508566145642086267779449671966118
-------------------------------------------------------------------------------------------------
8792893478724906376346595940397381414660944059455444526883826702343071776391783679870245781731806560482766608548081581236508566145642086267779449671966118
-------------------------------------------------------------------------------------------------
8792893478724906376346595940397381414660944059455444526883826702343071776391783679870245781731806560482766608548081581236508566145642086267779449671966118
-------------------------------------------------------------------------------------------------
8792893478724906376346595940397381414660944059455444526883826702343071776391783679870245781731806560482766608548081581236508566145642086267779449671966118
-------------------------------------------------------------------------------------------------



165
12463552721404751253490695835324349650981883927770596520186782503376071096600988354122723865466017167820845003619786620411189750345051762639744381058373026
-------------------------------------------------------------------------------------------------
12463552721404751253490695835324349650981883927770596520186782503376071096600988354122723865466017167820845003619786620411189750345051762639744381058373026
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
12463552721404751253490695835324349650981883927770596520186782503376071096600988354122723865466017167820845003619786620411189750345051762639744381058373026
-------------------------------------------------------------------------------------------------



165
87078028278582109477917254885939777152398010521949977392095579436332227653417124027996781454306793943605090550603608237589736149736979176795451963354740
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
805860562546272535642359562821227356724651128500871940563005839395594426604516433161020658870916929484554833995114265884677753385857715968157681349539653
-------------------------------------------------------------------------------------------------
805860562546272535642359562821227356724651128500871940563005839395594426604516433161020658870916929484554833995114265884677753385857715968157681349539653
-------------------------------------------------------------------------------------------------
805860562546272535642359562821227356724651128500871940563005839395594426604516433161020658870916929484554833995114265884677753385857715968157681349539653
-------------------------------------------------------------------------------------------------
805860562546272535642359562821227356724651128500871940563005839395594426604516433161020658870916929484554833995114265884677753385857715968157681349539653
-------------------------------------------------------------------------------------------------



165
1824199138990738112743911309396826439952171442890097194441514697652601407871415020768328703850897924653914103362489392203447802964085654615186411195443023
-------------------------------------------------------------------------------------------------
1824199138990738112743911309396826439952171442890097194441514697652601407871415020768328703850897924653914103362489392203447802964085654615186411195443023
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
1824199138990738112743911309396826439952171442890097194441514697652601407871415020768328703850897924653914103362489392203447802964085654615186411195443023
-------------------------------------------------------------------------------------------------



165
6919745992797178448051395568688745195060463423388829289263867102711846178994641317295055205083143173745826295736482568450769254251228787290570104250388907
-------------------------------------------------------------------------------------------------
6919745992797178448051395568688745195060463423388829289263867102711846178994641317295055205083143173745826295736482568450769254251228787290570104250388907
-------------------------------------------------------------------------------------------------
6919745992797178448051395568688745195060463423388829289263867102711846178994641317295055205083143173745826295736482568450769254251228787290570104250388907
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
2549693372089247963285325610151174262668802287026958329568322876455659053842127055924380452955349737061345824652801642581250405528737129168184992124934645
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
2549693372089247963285325610151174262668802287026958329568322876455659053842127055924380452955349737061345824652801642581250405528737129168184992124934645
-------------------------------------------------------------------------------------------------



165
11001788897310346829516784264672846383475730025136738105600064786735959514528994790817660138293571473721884521580647835261493681474939775565674717650680804
-------------------------------------------------------------------------------------------------
11001788897310346829516784264672846383475730025136738105600064786735959514528994790817660138293571473721884521580647835261493681474939775565674717650680804
-------------------------------------------------------------------------------------------------
11001788897310346829516784264672846383475730025136738105600064786735959514528994790817660138293571473721884521580647835261493681474939775565674717650680804
-------------------------------------------------------------------------------------------------
11001788897310346829516784264672846383475730025136738105600064786735959514528994790817660138293571473721884521580647835261493681474939775565674717650680804
-------------------------------------------------------------------------------------------------



165
8421210801714942255477921822268278368443902878882076788610216259371642168616487181331352456639532989735112544887586151341921866372984067107170197263762061
-------------------------------------------------------------------------------------------------
8421210801714942255477921822268278368443902878882076788610216259371642168616487181331352456639532989735112544887586151341921866372984067107170197263762061
-------------------------------------------------------------------------------------------------
8421210801714942255477921822268278368443902878882076788610216259371642168616487181331352456639532989735112544887586151341921866372984067107170197263762061
-------------------------------------------------------------------------------------------------
8421210801714942255477921822268278368443902878882076788610216259371642168616487181331352456639532989735112544887586151341921866372984067107170197263762061
-------------------------------------------------------------------------------------------------



165
5056764162347933392608616020296249644752511702192793440491444374403739542780837379355368703458657365636237897795484583146847987781678716755579253176752603
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 750, in rs_correct_msg
    err_pos = rs_find_errors(err_loc[::-1], len(msg_out), generator)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 694, in rs_find_errors
    raise ReedSolomonError("Too many (or few) errors found by Chien Search for the errata locator polynomial!")
reedsolo.ReedSolomonError: Too many (or few) errors found by Chien Search for the errata locator polynomial!

Wrong user!
-------------------------------------------------------------------------------------------------



165
8679366911639092586275871553471436221109931616575738888770419700398446601932295813793283161596184597445887477438513992294968577439132692660957217330426959
-------------------------------------------------------------------------------------------------
8679366911639092586275871553471436221109931616575738888770419700398446601932295813793283161596184597445887477438513992294968577439132692660957217330426959
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8119085938267798400676062218092678155688988576206039477936886590855715769094898875622173758894102054069978018833518784239173829817137789544455847186165964
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
8119085938267798400676062218092678155688988576206039477936886590855715769094898875622173758894102054069978018833518784239173829817137789544455847186165964
-------------------------------------------------------------------------------------------------
8119085938267798400676062218092678155688988576206039477936886590855715769094898875622173758894102054069978018833518784239173829817137789544455847186165964
-------------------------------------------------------------------------------------------------



165
636415915552927491287927806527668443096650188979580735675622882363002492981955124232778802642961488755315604195125292944148678428114110127641672540027611
-------------------------------------------------------------------------------------------------
636415915552927491287927806527668443096650188979580735675622882363002492981955124232778802642961488755315604195125292944148678428114110127641672540027611
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
12293610099422160696317555586547703951320998586952995408435587325063988610099892932397930977732971606573885930392493364085348948953665636134497548081886318
-------------------------------------------------------------------------------------------------
12293610099422160696317555586547703951320998586952995408435587325063988610099892932397930977732971606573885930392493364085348948953665636134497548081886318
-------------------------------------------------------------------------------------------------
12293610099422160696317555586547703951320998586952995408435587325063988610099892932397930977732971606573885930392493364085348948953665636134497548081886318
-------------------------------------------------------------------------------------------------
12293610099422160696317555586547703951320998586952995408435587325063988610099892932397930977732971606573885930392493364085348948953665636134497548081886318
-------------------------------------------------------------------------------------------------



165
2503339829287923469455322893164968428405928706719076161979974935706195500822606754429239691608815642171317962365917200443339599774258107912140280251242161
-------------------------------------------------------------------------------------------------
2503339829287923469455322893164968428405928706719076161979974935706195500822606754429239691608815642171317962365917200443339599774258107912140280251242161
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
2503339829287923469455322893164968428405928706719076161979974935706195500822606754429239691608815642171317962365917200443339599774258107912140280251242161
-------------------------------------------------------------------------------------------------



165
9396449786446313973996850374532942056407074991507446310520909356695006323222237356472071544311636032273581097441565882071248303820413694901149982602431976
-------------------------------------------------------------------------------------------------
9396449786446313973996850374532942056407074991507446310520909356695006323222237356472071544311636032273581097441565882071248303820413694901149982602431976
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
9644031545861119161026158111919753226307886907218338733535603749006979574684251076767104348370653138132506692248695391193519201572145438335104855707722408
-------------------------------------------------------------------------------------------------
9644031545861119161026158111919753226307886907218338733535603749006979574684251076767104348370653138132506692248695391193519201572145438335104855707722408
-------------------------------------------------------------------------------------------------
9644031545861119161026158111919753226307886907218338733535603749006979574684251076767104348370653138132506692248695391193519201572145438335104855707722408
-------------------------------------------------------------------------------------------------
9644031545861119161026158111919753226307886907218338733535603749006979574684251076767104348370653138132506692248695391193519201572145438335104855707722408
-------------------------------------------------------------------------------------------------



165
3531419225365621264194785925440835956582162520055235106761951444217507896812867637285301082492745432133632752810490735307503043352444332515888020147390517
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
3531419225365621264194785925440835956582162520055235106761951444217507896812867637285301082492745432133632752810490735307503043352444332515888020147390517
-------------------------------------------------------------------------------------------------



165
11770346055420680246400784052039942930604185665586558827229358819358173482842107307326125779934573659076404343692148334104258842422099829913778395940650430
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
1947453764963072094023263773924658292695154149152188594518651937041939504981058079393159626216532945516089928489371433634238816747202733858403784254009088
-------------------------------------------------------------------------------------------------
1947453764963072094023263773924658292695154149152188594518651937041939504981058079393159626216532945516089928489371433634238816747202733858403784254009088
-------------------------------------------------------------------------------------------------
1947453764963072094023263773924658292695154149152188594518651937041939504981058079393159626216532945516089928489371433634238816747202733858403784254009088
-------------------------------------------------------------------------------------------------
1947453764963072094023263773924658292695154149152188594518651937041939504981058079393159626216532945516089928489371433634238816747202733858403784254009088
-------------------------------------------------------------------------------------------------



165
11806097522070862567309880236468541557783096738398632335999108345979103424217641232323734433627167858696474718770877131500259727207610015378861888744767947
-------------------------------------------------------------------------------------------------
11806097522070862567309880236468541557783096738398632335999108345979103424217641232323734433627167858696474718770877131500259727207610015378861888744767947
-------------------------------------------------------------------------------------------------
11806097522070862567309880236468541557783096738398632335999108345979103424217641232323734433627167858696474718770877131500259727207610015378861888744767947
-------------------------------------------------------------------------------------------------
11806097522070862567309880236468541557783096738398632335999108345979103424217641232323734433627167858696474718770877131500259727207610015378861888744767947
-------------------------------------------------------------------------------------------------



165
13152646379618517067517022210403876620450697784257501445715132384911082744317907130549319200811905499461548159824564598218042934756158827706784044928974126
-------------------------------------------------------------------------------------------------
13152646379618517067517022210403876620450697784257501445715132384911082744317907130549319200811905499461548159824564598218042934756158827706784044928974126
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
5108267938251465674570421179406266799211928529575211655180382748399792896395254977893826342473494783497504784020369484094393751825435976696810621865147112
-------------------------------------------------------------------------------------------------
5108267938251465674570421179406266799211928529575211655180382748399792896395254977893826342473494783497504784020369484094393751825435976696810621865147112
-------------------------------------------------------------------------------------------------
5108267938251465674570421179406266799211928529575211655180382748399792896395254977893826342473494783497504784020369484094393751825435976696810621865147112
-------------------------------------------------------------------------------------------------
5108267938251465674570421179406266799211928529575211655180382748399792896395254977893826342473494783497504784020369484094393751825435976696810621865147112
-------------------------------------------------------------------------------------------------



165
1020464119918710885067263624402420708850863693223165319588371650405118292178000703616267126526128790281144120076039834491936615592130397478525084259292377
-------------------------------------------------------------------------------------------------
1020464119918710885067263624402420708850863693223165319588371650405118292178000703616267126526128790281144120076039834491936615592130397478525084259292377
-------------------------------------------------------------------------------------------------
1020464119918710885067263624402420708850863693223165319588371650405118292178000703616267126526128790281144120076039834491936615592130397478525084259292377
-------------------------------------------------------------------------------------------------
1020464119918710885067263624402420708850863693223165319588371650405118292178000703616267126526128790281144120076039834491936615592130397478525084259292377
-------------------------------------------------------------------------------------------------



165
7634889401428277601673944703771576622457960168825132274216621846687041490349991954612391804959110465629256815125618682936961741512889520090200687470430882
-------------------------------------------------------------------------------------------------
7634889401428277601673944703771576622457960168825132274216621846687041490349991954612391804959110465629256815125618682936961741512889520090200687470430882
-------------------------------------------------------------------------------------------------
7634889401428277601673944703771576622457960168825132274216621846687041490349991954612391804959110465629256815125618682936961741512889520090200687470430882
-------------------------------------------------------------------------------------------------
7634889401428277601673944703771576622457960168825132274216621846687041490349991954612391804959110465629256815125618682936961741512889520090200687470430882
-------------------------------------------------------------------------------------------------



165
6875559664921273155188433827379232355908579618565320106879065915193076709266820795611731601748399683374464644160804676424367641821751651772906386490499969
-------------------------------------------------------------------------------------------------
6875559664921273155188433827379232355908579618565320106879065915193076709266820795611731601748399683374464644160804676424367641821751651772906386490499969
-------------------------------------------------------------------------------------------------
6875559664921273155188433827379232355908579618565320106879065915193076709266820795611731601748399683374464644160804676424367641821751651772906386490499969
-------------------------------------------------------------------------------------------------
6875559664921273155188433827379232355908579618565320106879065915193076709266820795611731601748399683374464644160804676424367641821751651772906386490499969
-------------------------------------------------------------------------------------------------



165
8234975076034433303583217559392441978852632046401117741087984926298348863611125950703208911339704517847848298478701902214476525062629475249543024692226992
-------------------------------------------------------------------------------------------------
8234975076034433303583217559392441978852632046401117741087984926298348863611125950703208911339704517847848298478701902214476525062629475249543024692226992
-------------------------------------------------------------------------------------------------
8234975076034433303583217559392441978852632046401117741087984926298348863611125950703208911339704517847848298478701902214476525062629475249543024692226992
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
2249743494530223307003258316693216491836233529997559658251606166971175936253807473799060724163607502133439995273172796514452856119923656833411518400185132
-------------------------------------------------------------------------------------------------
2249743494530223307003258316693216491836233529997559658251606166971175936253807473799060724163607502133439995273172796514452856119923656833411518400185132
-------------------------------------------------------------------------------------------------
2249743494530223307003258316693216491836233529997559658251606166971175936253807473799060724163607502133439995273172796514452856119923656833411518400185132
-------------------------------------------------------------------------------------------------
2249743494530223307003258316693216491836233529997559658251606166971175936253807473799060724163607502133439995273172796514452856119923656833411518400185132
-------------------------------------------------------------------------------------------------



165
7406641725214897581038724968076280927984215519954811936843225060797521028143042468602691119230477679127414108223096252731525576676894872946434519170319844
-------------------------------------------------------------------------------------------------
7406641725214897581038724968076280927984215519954811936843225060797521028143042468602691119230477679127414108223096252731525576676894872946434519170319844
-------------------------------------------------------------------------------------------------
7406641725214897581038724968076280927984215519954811936843225060797521028143042468602691119230477679127414108223096252731525576676894872946434519170319844
-------------------------------------------------------------------------------------------------
7406641725214897581038724968076280927984215519954811936843225060797521028143042468602691119230477679127414108223096252731525576676894872946434519170319844
-------------------------------------------------------------------------------------------------



165
11598114381942356695009859348718808678026375398992794109241988390498540011509386477762917127143968136787501563934594043198254359033042960303991059153073359
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
11598114381942356695009859348718808678026375398992794109241988390498540011509386477762917127143968136787501563934594043198254359033042960303991059153073359
-------------------------------------------------------------------------------------------------
11598114381942356695009859348718808678026375398992794109241988390498540011509386477762917127143968136787501563934594043198254359033042960303991059153073359
-------------------------------------------------------------------------------------------------



165
7087801920718762438782983085425064277541592125215375207067065592781437666115455450323609750315204867727708286092391312750405694563898605225841697842833074
-------------------------------------------------------------------------------------------------
7087801920718762438782983085425064277541592125215375207067065592781437666115455450323609750315204867727708286092391312750405694563898605225841697842833074
-------------------------------------------------------------------------------------------------
7087801920718762438782983085425064277541592125215375207067065592781437666115455450323609750315204867727708286092391312750405694563898605225841697842833074
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
2546782974052766214459616379970448673745021896699275710755579941014672327448608120314714979752499200854802462831123157662437921531904090906143814686220684
-------------------------------------------------------------------------------------------------
2546782974052766214459616379970448673745021896699275710755579941014672327448608120314714979752499200854802462831123157662437921531904090906143814686220684
-------------------------------------------------------------------------------------------------
2546782974052766214459616379970448673745021896699275710755579941014672327448608120314714979752499200854802462831123157662437921531904090906143814686220684
-------------------------------------------------------------------------------------------------
2546782974052766214459616379970448673745021896699275710755579941014672327448608120314714979752499200854802462831123157662437921531904090906143814686220684
-------------------------------------------------------------------------------------------------



165
11453046851422884451735721933881572952319634726598586339262310525077602495016021118574624281367027063491183013448287766840781426410226327586648934033657297
-------------------------------------------------------------------------------------------------
11453046851422884451735721933881572952319634726598586339262310525077602495016021118574624281367027063491183013448287766840781426410226327586648934033657297
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
11453046851422884451735721933881572952319634726598586339262310525077602495016021118574624281367027063491183013448287766840781426410226327586648934033657297
-------------------------------------------------------------------------------------------------



165
10161264326852462125268180939341281142819339156699341817102570572736069248981225888378508257388662808766513931160899486169370041614642898067256858482243276
-------------------------------------------------------------------------------------------------
10161264326852462125268180939341281142819339156699341817102570572736069248981225888378508257388662808766513931160899486169370041614642898067256858482243276
-------------------------------------------------------------------------------------------------
10161264326852462125268180939341281142819339156699341817102570572736069248981225888378508257388662808766513931160899486169370041614642898067256858482243276
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
9182853161221283895870850501246230578443812201141601613435135047984555217153054474661197570597829018802783610099706546598024394895446016753535664079314682
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
9182853161221283895870850501246230578443812201141601613435135047984555217153054474661197570597829018802783610099706546598024394895446016753535664079314682
-------------------------------------------------------------------------------------------------
9182853161221283895870850501246230578443812201141601613435135047984555217153054474661197570597829018802783610099706546598024394895446016753535664079314682
-------------------------------------------------------------------------------------------------



165
12976191076830268908199693117161913679308347503862369416075475156392620669507209849882889904976547857730201499579772402468943220536840873452852823434374006
-------------------------------------------------------------------------------------------------
12976191076830268908199693117161913679308347503862369416075475156392620669507209849882889904976547857730201499579772402468943220536840873452852823434374006
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
12976191076830268908199693117161913679308347503862369416075475156392620669507209849882889904976547857730201499579772402468943220536840873452852823434374006
-------------------------------------------------------------------------------------------------



165
8618844104249481826646523915883872704620723189567786903065016366766589178772093772220244147657755059527420544751313204233903657473027020079918795537199521
-------------------------------------------------------------------------------------------------
8618844104249481826646523915883872704620723189567786903065016366766589178772093772220244147657755059527420544751313204233903657473027020079918795537199521
-------------------------------------------------------------------------------------------------
8618844104249481826646523915883872704620723189567786903065016366766589178772093772220244147657755059527420544751313204233903657473027020079918795537199521
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
6655763029977229551750873349531551869198795878137560795122466139483766388948566071742601871176822293571459264071247274293807396273483412594177949517930468
-------------------------------------------------------------------------------------------------
6655763029977229551750873349531551869198795878137560795122466139483766388948566071742601871176822293571459264071247274293807396273483412594177949517930468
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
6655763029977229551750873349531551869198795878137560795122466139483766388948566071742601871176822293571459264071247274293807396273483412594177949517930468
-------------------------------------------------------------------------------------------------



165
13375450606742216912605937942434621705839302518641280765458156813082881943289676179287059658345127680730590970215580791156718374011998974972356920503020810
-------------------------------------------------------------------------------------------------
13375450606742216912605937942434621705839302518641280765458156813082881943289676179287059658345127680730590970215580791156718374011998974972356920503020810
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
13375450606742216912605937942434621705839302518641280765458156813082881943289676179287059658345127680730590970215580791156718374011998974972356920503020810
-------------------------------------------------------------------------------------------------



165
8978364547172453785692296263377589297782269444278869141048920897626579143933912160790182029392301229132728004332324644393960810380981917027205143579108923
-------------------------------------------------------------------------------------------------
8978364547172453785692296263377589297782269444278869141048920897626579143933912160790182029392301229132728004332324644393960810380981917027205143579108923
-------------------------------------------------------------------------------------------------
8978364547172453785692296263377589297782269444278869141048920897626579143933912160790182029392301229132728004332324644393960810380981917027205143579108923
-------------------------------------------------------------------------------------------------
8978364547172453785692296263377589297782269444278869141048920897626579143933912160790182029392301229132728004332324644393960810380981917027205143579108923
-------------------------------------------------------------------------------------------------



165
10954784791925083256682241203346639321260629356768665033680970412561149916090843882603636684831311929064349165093447905240321511068357620242427999827604467
-------------------------------------------------------------------------------------------------
10954784791925083256682241203346639321260629356768665033680970412561149916090843882603636684831311929064349165093447905240321511068357620242427999827604467
-------------------------------------------------------------------------------------------------
10954784791925083256682241203346639321260629356768665033680970412561149916090843882603636684831311929064349165093447905240321511068357620242427999827604467
-------------------------------------------------------------------------------------------------
10954784791925083256682241203346639321260629356768665033680970412561149916090843882603636684831311929064349165093447905240321511068357620242427999827604467
-------------------------------------------------------------------------------------------------



165
12368315070770549208271136540165699787340828787605865362396369146121356917191403951029416466520748279724776422280452505201864784537825199262085800346040465
-------------------------------------------------------------------------------------------------
12368315070770549208271136540165699787340828787605865362396369146121356917191403951029416466520748279724776422280452505201864784537825199262085800346040465
-------------------------------------------------------------------------------------------------
12368315070770549208271136540165699787340828787605865362396369146121356917191403951029416466520748279724776422280452505201864784537825199262085800346040465
-------------------------------------------------------------------------------------------------
12368315070770549208271136540165699787340828787605865362396369146121356917191403951029416466520748279724776422280452505201864784537825199262085800346040465
-------------------------------------------------------------------------------------------------



165
10189552774700082326772573360883508212245869453955126381824852825440363995037489877515260662733761837324161080078911298301907012570889310430138628585681167
-------------------------------------------------------------------------------------------------
10189552774700082326772573360883508212245869453955126381824852825440363995037489877515260662733761837324161080078911298301907012570889310430138628585681167
-------------------------------------------------------------------------------------------------
10189552774700082326772573360883508212245869453955126381824852825440363995037489877515260662733761837324161080078911298301907012570889310430138628585681167
-------------------------------------------------------------------------------------------------
10189552774700082326772573360883508212245869453955126381824852825440363995037489877515260662733761837324161080078911298301907012570889310430138628585681167
-------------------------------------------------------------------------------------------------



165
925266552359486765727733742343962369466017901543891862324455198171509970857398929499307840352740959148673788889891937645269444825240738368048105415054929
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
88408981812355869441996399784054981387736630039118613649400138157204299656184024238027075940269644461389425474399971626875107862718552744077277404816152
-------------------------------------------------------------------------------------------------
88408981812355869441996399784054981387736630039118613649400138157204299656184024238027075940269644461389425474399971626875107862718552744077277404816152
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
9586925012581032266370081438285484045737303592025854794711220691912417661304199123964793863754342125552517996786613896505212320564745389521498306201730061
-------------------------------------------------------------------------------------------------
9586925012581032266370081438285484045737303592025854794711220691912417661304199123964793863754342125552517996786613896505212320564745389521498306201730061
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
9586925012581032266370081438285484045737303592025854794711220691912417661304199123964793863754342125552517996786613896505212320564745389521498306201730061
-------------------------------------------------------------------------------------------------



165
4099843431964022437848559605256529081925948640253557250314539609559500091761645663783695882711141530865782839756350932696475011396646759887987362410772488
-------------------------------------------------------------------------------------------------
4099843431964022437848559605256529081925948640253557250314539609559500091761645663783695882711141530865782839756350932696475011396646759887987362410772488
-------------------------------------------------------------------------------------------------
4099843431964022437848559605256529081925948640253557250314539609559500091761645663783695882711141530865782839756350932696475011396646759887987362410772488
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
3582666507217899506721022179926166043622031213519765992925620644046898516016475729109102225538919576606052069312424916549464673796398347619267009387808705
-------------------------------------------------------------------------------------------------
3582666507217899506721022179926166043622031213519765992925620644046898516016475729109102225538919576606052069312424916549464673796398347619267009387808705
-------------------------------------------------------------------------------------------------
3582666507217899506721022179926166043622031213519765992925620644046898516016475729109102225538919576606052069312424916549464673796398347619267009387808705
-------------------------------------------------------------------------------------------------
3582666507217899506721022179926166043622031213519765992925620644046898516016475729109102225538919576606052069312424916549464673796398347619267009387808705
-------------------------------------------------------------------------------------------------



165
4364202148348015385119526445101040917325949817306741671356059409613857942419985901516071607745292347937607474697933225595118906327305137933602057782145331
-------------------------------------------------------------------------------------------------
4364202148348015385119526445101040917325949817306741671356059409613857942419985901516071607745292347937607474697933225595118906327305137933602057782145331
-------------------------------------------------------------------------------------------------
4364202148348015385119526445101040917325949817306741671356059409613857942419985901516071607745292347937607474697933225595118906327305137933602057782145331
-------------------------------------------------------------------------------------------------
4364202148348015385119526445101040917325949817306741671356059409613857942419985901516071607745292347937607474697933225595118906327305137933602057782145331
-------------------------------------------------------------------------------------------------



165
8622511961629568003199289859030576984070039352456359342957553203307746456588945841441983456498017129776427661626041543398176287678493899789954276626666815
-------------------------------------------------------------------------------------------------
8622511961629568003199289859030576984070039352456359342957553203307746456588945841441983456498017129776427661626041543398176287678493899789954276626666815
-------------------------------------------------------------------------------------------------
8622511961629568003199289859030576984070039352456359342957553203307746456588945841441983456498017129776427661626041543398176287678493899789954276626666815
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
4466424647171657678694016708358798049878770831989576747540568801080417639109026172967381313610799186199659619929105147235898602880090825505419707694978998
-------------------------------------------------------------------------------------------------
4466424647171657678694016708358798049878770831989576747540568801080417639109026172967381313610799186199659619929105147235898602880090825505419707694978998
-------------------------------------------------------------------------------------------------
4466424647171657678694016708358798049878770831989576747540568801080417639109026172967381313610799186199659619929105147235898602880090825505419707694978998
-------------------------------------------------------------------------------------------------
4466424647171657678694016708358798049878770831989576747540568801080417639109026172967381313610799186199659619929105147235898602880090825505419707694978998
-------------------------------------------------------------------------------------------------



165
1498216720588608992723600145193648983593272603906840531385669333965578236857849977388177274737341136971017330603335231484475477753801651770622782737662943
-------------------------------------------------------------------------------------------------
1498216720588608992723600145193648983593272603906840531385669333965578236857849977388177274737341136971017330603335231484475477753801651770622782737662943
-------------------------------------------------------------------------------------------------
1498216720588608992723600145193648983593272603906840531385669333965578236857849977388177274737341136971017330603335231484475477753801651770622782737662943
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
11147360261448590799612048731056254252430304300217057193589529372101149194495116423793261128137281020792566224163655048364168931518412018528801909154908437
-------------------------------------------------------------------------------------------------
11147360261448590799612048731056254252430304300217057193589529372101149194495116423793261128137281020792566224163655048364168931518412018528801909154908437
-------------------------------------------------------------------------------------------------
11147360261448590799612048731056254252430304300217057193589529372101149194495116423793261128137281020792566224163655048364168931518412018528801909154908437
-------------------------------------------------------------------------------------------------
11147360261448590799612048731056254252430304300217057193589529372101149194495116423793261128137281020792566224163655048364168931518412018528801909154908437
-------------------------------------------------------------------------------------------------



165
56906714073503030723081018773161335914242930512226486160607247766085479055681485879557424626739750656885956652242355712801096995632149487147719156624743
-------------------------------------------------------------------------------------------------
56906714073503030723081018773161335914242930512226486160607247766085479055681485879557424626739750656885956652242355712801096995632149487147719156624743
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
56906714073503030723081018773161335914242930512226486160607247766085479055681485879557424626739750656885956652242355712801096995632149487147719156624743
-------------------------------------------------------------------------------------------------



165
12576363304017661317136558125223165175256352094961008053901478385125294320012052159748356872454464977440771873432166271315146437801471355717733402582362344
-------------------------------------------------------------------------------------------------
12576363304017661317136558125223165175256352094961008053901478385125294320012052159748356872454464977440771873432166271315146437801471355717733402582362344
-------------------------------------------------------------------------------------------------
12576363304017661317136558125223165175256352094961008053901478385125294320012052159748356872454464977440771873432166271315146437801471355717733402582362344
-------------------------------------------------------------------------------------------------
12576363304017661317136558125223165175256352094961008053901478385125294320012052159748356872454464977440771873432166271315146437801471355717733402582362344
-------------------------------------------------------------------------------------------------



165
3476249346170498474017905791359662268748398700826211622566847700944054610474055974959884422491982436534279427007775687691599207600738833669659844044126844
-------------------------------------------------------------------------------------------------
3476249346170498474017905791359662268748398700826211622566847700944054610474055974959884422491982436534279427007775687691599207600738833669659844044126844
-------------------------------------------------------------------------------------------------
3476249346170498474017905791359662268748398700826211622566847700944054610474055974959884422491982436534279427007775687691599207600738833669659844044126844
-------------------------------------------------------------------------------------------------
3476249346170498474017905791359662268748398700826211622566847700944054610474055974959884422491982436534279427007775687691599207600738833669659844044126844
-------------------------------------------------------------------------------------------------



165
3856133284598448290530268133035968951825813551237628479214716430276062242346874253545608866901804343653065041980074788505488417814033159272912737506100363
-------------------------------------------------------------------------------------------------
3856133284598448290530268133035968951825813551237628479214716430276062242346874253545608866901804343653065041980074788505488417814033159272912737506100363
-------------------------------------------------------------------------------------------------
3856133284598448290530268133035968951825813551237628479214716430276062242346874253545608866901804343653065041980074788505488417814033159272912737506100363
-------------------------------------------------------------------------------------------------
3856133284598448290530268133035968951825813551237628479214716430276062242346874253545608866901804343653065041980074788505488417814033159272912737506100363
-------------------------------------------------------------------------------------------------



165
7416827031413888519972488327667684265565815952369733918615483606848978440620135800357735810257387683181914409312856940414353920230079646090658062089220820
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
3613902577805798538465897155098303624040100047441740854064474470430016227742944972539616484695782721857471612257418390242744114260755341165693015155280975
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
3613902577805798538465897155098303624040100047441740854064474470430016227742944972539616484695782721857471612257418390242744114260755341165693015155280975
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8790367561548715538857183089911505604370841483327381132353380420558547957887401330303862588354325328315720883090647184167829915167477653569487479266844647
-------------------------------------------------------------------------------------------------
8790367561548715538857183089911505604370841483327381132353380420558547957887401330303862588354325328315720883090647184167829915167477653569487479266844647
-------------------------------------------------------------------------------------------------
8790367561548715538857183089911505604370841483327381132353380420558547957887401330303862588354325328315720883090647184167829915167477653569487479266844647
-------------------------------------------------------------------------------------------------
8790367561548715538857183089911505604370841483327381132353380420558547957887401330303862588354325328315720883090647184167829915167477653569487479266844647
-------------------------------------------------------------------------------------------------



165
1161445380747138992656346104247709172641776127405600691329764741393370930114398736959073711923582293963614784412553900755572270658115260307990312774915500
-------------------------------------------------------------------------------------------------
1161445380747138992656346104247709172641776127405600691329764741393370930114398736959073711923582293963614784412553900755572270658115260307990312774915500
-------------------------------------------------------------------------------------------------
1161445380747138992656346104247709172641776127405600691329764741393370930114398736959073711923582293963614784412553900755572270658115260307990312774915500
-------------------------------------------------------------------------------------------------
1161445380747138992656346104247709172641776127405600691329764741393370930114398736959073711923582293963614784412553900755572270658115260307990312774915500
-------------------------------------------------------------------------------------------------



165
11989816183062403262405338486902168462922212628273073491199758322510700416110220940082233022384095629127395339578713096677863878322402804840657644560296856
-------------------------------------------------------------------------------------------------
11989816183062403262405338486902168462922212628273073491199758322510700416110220940082233022384095629127395339578713096677863878322402804840657644560296856
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
11989816183062403262405338486902168462922212628273073491199758322510700416110220940082233022384095629127395339578713096677863878322402804840657644560296856
-------------------------------------------------------------------------------------------------



165
8008650139361025911609519876679938944690285806916391970420737387258558128238506812066786212044882333866558043739341553080251750062527598871397990348248893
-------------------------------------------------------------------------------------------------
8008650139361025911609519876679938944690285806916391970420737387258558128238506812066786212044882333866558043739341553080251750062527598871397990348248893
-------------------------------------------------------------------------------------------------
8008650139361025911609519876679938944690285806916391970420737387258558128238506812066786212044882333866558043739341553080251750062527598871397990348248893
-------------------------------------------------------------------------------------------------
8008650139361025911609519876679938944690285806916391970420737387258558128238506812066786212044882333866558043739341553080251750062527598871397990348248893
-------------------------------------------------------------------------------------------------



165
12601525963343632209255512891237456682045508907372341920504725402878671681356967873512595329701614227151244548970178308281469516487309756023364564077402883
-------------------------------------------------------------------------------------------------
12601525963343632209255512891237456682045508907372341920504725402878671681356967873512595329701614227151244548970178308281469516487309756023364564077402883
-------------------------------------------------------------------------------------------------
12601525963343632209255512891237456682045508907372341920504725402878671681356967873512595329701614227151244548970178308281469516487309756023364564077402883
-------------------------------------------------------------------------------------------------
12601525963343632209255512891237456682045508907372341920504725402878671681356967873512595329701614227151244548970178308281469516487309756023364564077402883
-------------------------------------------------------------------------------------------------



165
1269460514518209931012084828571090495060854499233230627115541952029324058591584030718307669065101826357869670796967420347881210040276486538360956078018265
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
1269460514518209931012084828571090495060854499233230627115541952029324058591584030718307669065101826357869670796967420347881210040276486538360956078018265
-------------------------------------------------------------------------------------------------
1269460514518209931012084828571090495060854499233230627115541952029324058591584030718307669065101826357869670796967420347881210040276486538360956078018265
-------------------------------------------------------------------------------------------------



165
9424538413416680698793869905886264753067856618503471892129526926933776348716811905174541681322339262840662315800245052730671651092182709465243813405593525
-------------------------------------------------------------------------------------------------
9424538413416680698793869905886264753067856618503471892129526926933776348716811905174541681322339262840662315800245052730671651092182709465243813405593525
-------------------------------------------------------------------------------------------------
9424538413416680698793869905886264753067856618503471892129526926933776348716811905174541681322339262840662315800245052730671651092182709465243813405593525
-------------------------------------------------------------------------------------------------
9424538413416680698793869905886264753067856618503471892129526926933776348716811905174541681322339262840662315800245052730671651092182709465243813405593525
-------------------------------------------------------------------------------------------------



165
6837999896675986013437942390327143831231249523614413354707252383422837082891204030068564684904187278773588489255047499758029873228228483546191619084461779
-------------------------------------------------------------------------------------------------
6837999896675986013437942390327143831231249523614413354707252383422837082891204030068564684904187278773588489255047499758029873228228483546191619084461779
-------------------------------------------------------------------------------------------------
6837999896675986013437942390327143831231249523614413354707252383422837082891204030068564684904187278773588489255047499758029873228228483546191619084461779
-------------------------------------------------------------------------------------------------
6837999896675986013437942390327143831231249523614413354707252383422837082891204030068564684904187278773588489255047499758029873228228483546191619084461779
-------------------------------------------------------------------------------------------------



165
985848384727809689658852206398737004739829017477455390940970245693830411940134074392329062746770629597694489451419952707690764211821242823486062387835579
-------------------------------------------------------------------------------------------------
985848384727809689658852206398737004739829017477455390940970245693830411940134074392329062746770629597694489451419952707690764211821242823486062387835579
-------------------------------------------------------------------------------------------------
985848384727809689658852206398737004739829017477455390940970245693830411940134074392329062746770629597694489451419952707690764211821242823486062387835579
-------------------------------------------------------------------------------------------------
985848384727809689658852206398737004739829017477455390940970245693830411940134074392329062746770629597694489451419952707690764211821242823486062387835579
-------------------------------------------------------------------------------------------------



165
12761611392835223461298502885710300774972516489124920061363615460566615760448958585525638182183788426051730539548374326060850043772449144522578464070301494
-------------------------------------------------------------------------------------------------
12761611392835223461298502885710300774972516489124920061363615460566615760448958585525638182183788426051730539548374326060850043772449144522578464070301494
-------------------------------------------------------------------------------------------------
12761611392835223461298502885710300774972516489124920061363615460566615760448958585525638182183788426051730539548374326060850043772449144522578464070301494
-------------------------------------------------------------------------------------------------
12761611392835223461298502885710300774972516489124920061363615460566615760448958585525638182183788426051730539548374326060850043772449144522578464070301494
-------------------------------------------------------------------------------------------------



165
7676885924226739856281617776468082253041405937042051908484461941352821900170177532653549212414412785005992669398072953806960316173620415623545338858746394
-------------------------------------------------------------------------------------------------
7676885924226739856281617776468082253041405937042051908484461941352821900170177532653549212414412785005992669398072953806960316173620415623545338858746394
-------------------------------------------------------------------------------------------------
7676885924226739856281617776468082253041405937042051908484461941352821900170177532653549212414412785005992669398072953806960316173620415623545338858746394
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------



165
8908165703058938861539886632921020182322928409678216338967080983515967329077416583287224425728351507536890484038203379241364772969459472927421726367804687
-------------------------------------------------------------------------------------------------
8908165703058938861539886632921020182322928409678216338967080983515967329077416583287224425728351507536890484038203379241364772969459472927421726367804687
-------------------------------------------------------------------------------------------------
8908165703058938861539886632921020182322928409678216338967080983515967329077416583287224425728351507536890484038203379241364772969459472927421726367804687
-------------------------------------------------------------------------------------------------
8908165703058938861539886632921020182322928409678216338967080983515967329077416583287224425728351507536890484038203379241364772969459472927421726367804687
-------------------------------------------------------------------------------------------------



165
4692612109877406642493457989089076048656849825006963324584528528439989076856351701451131276305931814307327684119888473666831844216534506482058038017232592
-------------------------------------------------------------------------------------------------
4692612109877406642493457989089076048656849825006963324584528528439989076856351701451131276305931814307327684119888473666831844216534506482058038017232592
-------------------------------------------------------------------------------------------------
4692612109877406642493457989089076048656849825006963324584528528439989076856351701451131276305931814307327684119888473666831844216534506482058038017232592
-------------------------------------------------------------------------------------------------
4692612109877406642493457989089076048656849825006963324584528528439989076856351701451131276305931814307327684119888473666831844216534506482058038017232592
-------------------------------------------------------------------------------------------------



165
5616775750353359104366247316023462313931103244835701926841549768792641457060473690679674787888031118388092186353160304077645703266561839927959097531655714
-------------------------------------------------------------------------------------------------
5616775750353359104366247316023462313931103244835701926841549768792641457060473690679674787888031118388092186353160304077645703266561839927959097531655714
-------------------------------------------------------------------------------------------------
5616775750353359104366247316023462313931103244835701926841549768792641457060473690679674787888031118388092186353160304077645703266561839927959097531655714
-------------------------------------------------------------------------------------------------
5616775750353359104366247316023462313931103244835701926841549768792641457060473690679674787888031118388092186353160304077645703266561839927959097531655714
-------------------------------------------------------------------------------------------------



165
1913342180636469177092404469127434062295984538475833698749981422432626977349188700586332782209449923359983477021950620855340569421988419792166698130522727
-------------------------------------------------------------------------------------------------
1913342180636469177092404469127434062295984538475833698749981422432626977349188700586332782209449923359983477021950620855340569421988419792166698130522727
-------------------------------------------------------------------------------------------------
1913342180636469177092404469127434062295984538475833698749981422432626977349188700586332782209449923359983477021950620855340569421988419792166698130522727
-------------------------------------------------------------------------------------------------
1913342180636469177092404469127434062295984538475833698749981422432626977349188700586332782209449923359983477021950620855340569421988419792166698130522727
-------------------------------------------------------------------------------------------------



165
7190632346541894202658705733140651799831514082765488447163626577220327115889522701826232301575820034720572517216749896728487374694365080446694429593068835
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/Andrea/Desktop/Main/City/Individual Project/Source code/private_template_scheme/authentication.py", line 52, in authentication
    decoded_features = rsc.decode(padded_features)[0]
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 940, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 748, in rs_correct_msg
    err_loc = rs_find_error_locator(fsynd, nsym, erase_count=len(erase_pos))
  File "/home/bread98/.local/lib/python3.8/site-packages/reedsolo.py", line 659, in rs_find_error_locator
    raise ReedSolomonError("Too many errors to correct")
reedsolo.ReedSolomonError: Too many errors to correct

Wrong user!
-------------------------------------------------------------------------------------------------
7190632346541894202658705733140651799831514082765488447163626577220327115889522701826232301575820034720572517216749896728487374694365080446694429593068835
-------------------------------------------------------------------------------------------------



165
6610477244755416219589650883469292029374919270824690290460134050997534573236413304677738164404789319710470230923926770628300456915143858122649592139357501
-------------------------------------------------------------------------------------------------
6610477244755416219589650883469292029374919270824690290460134050997534573236413304677738164404789319710470230923926770628300456915143858122649592139357501
-------------------------------------------------------------------------------------------------
6610477244755416219589650883469292029374919270824690290460134050997534573236413304677738164404789319710470230923926770628300456915143858122649592139357501
-------------------------------------------------------------------------------------------------
6610477244755416219589650883469292029374919270824690290460134050997534573236413304677738164404789319710470230923926770628300456915143858122649592139357501
-------------------------------------------------------------------------------------------------



The FRR is: 0.21064814814814814
